### ISSUE TITLE
Make scroll bar dark theme on all subdomains

### ISSUE THREAD

**Issue by mateimarica** [mateimarica/mateimarica.dev#7]
Just like how its done on files.mateimarica.dev

```css
/* width */
::-webkit-scrollbar {
	width: 15px;
}

/* Track */
::-webkit-scrollbar-track {
	background: #131416;;
}

/* Handle */
::-webkit-scrollbar-thumb {
	background: #3a3f44;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
	background: #555;
}
```
